[2024-05-04T11:35:22.249+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:35:22.356+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_products scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:35:22.401+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_products scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:35:22.403+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-04T11:35:22.481+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_products> on 2024-05-03 00:00:00+00:00
[2024-05-04T11:35:22.543+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T11:35:22.564+0000] {standard_task_runner.py:63} INFO - Started process 9451 to run task
[2024-05-04T11:35:22.552+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_products', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpzsdrralc']
[2024-05-04T11:35:22.570+0000] {standard_task_runner.py:91} INFO - Job 171: Subtask gcs_to_bq_products
[2024-05-04T11:35:22.848+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_products scheduled__2024-05-03T00:00:00+00:00 [running]> on host d4c1d9b975b8
[2024-05-04T11:35:24.725+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_products' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T11:35:24.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T11:35:24.745+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T11:35:24.753+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-04T11:35:24.755+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-05-04T11:35:24.963+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: order.olist_products_dataset; using project "project-capstone-422211"
[2024-05-04T11:35:24.971+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'project-capstone-422211', 'datasetId': 'order', 'tableId': 'olist_products_dataset'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://storage-capstone/olist_products_dataset.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-04T11:35:24.974+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_products_2024_05_03T00_00_00_00_00_ad26f04205a6184b7f5706afbb62ab9e
[2024-05-04T11:35:29.631+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T11:35:29.632+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://storage-capstone/olist_products_dataset.csv; reason: notFound, message: Not found: URI gs://storage-capstone/olist_products_dataset.csv
[2024-05-04T11:35:29.643+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_products, execution_date=20240503T000000, start_date=20240504T113522, end_date=20240504T113529
[2024-05-04T11:35:29.658+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 171 for task gcs_to_bq_products (404 Not found: URI gs://storage-capstone/olist_products_dataset.csv; reason: notFound, message: Not found: URI gs://storage-capstone/olist_products_dataset.csv; 9451)
[2024-05-04T11:35:29.694+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T11:35:29.707+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:35:29.714+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
