[2024-05-04T11:38:34.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:38:35.028+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:38:35.132+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:38:35.132+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-04T11:38:35.226+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_sellers> on 2024-05-03 00:00:00+00:00
[2024-05-04T11:38:35.265+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11063) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T11:38:35.256+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_sellers', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpd80_n4mq']
[2024-05-04T11:38:35.278+0000] {standard_task_runner.py:91} INFO - Job 198: Subtask gcs_to_bq_sellers
[2024-05-04T11:38:35.276+0000] {standard_task_runner.py:63} INFO - Started process 11181 to run task
[2024-05-04T11:38:35.527+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-05-03T00:00:00+00:00 [running]> on host d4c1d9b975b8
[2024-05-04T11:38:37.274+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_sellers' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T11:38:37.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T11:38:37.346+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T11:38:37.399+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-04T11:38:37.403+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-05-04T11:38:37.641+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: order.olist_sellers_dataset; using project "project-capstone-422211"
[2024-05-04T11:38:37.642+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'project-capstone-422211', 'datasetId': 'order', 'tableId': 'olist_sellers_dataset'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://storage-capstone/olist_sellers_dataset.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-04T11:38:37.643+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_sellers_2024_05_03T00_00_00_00_00_b1778053564b8efc82615c9d3ab21e92
[2024-05-04T11:38:40.263+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T11:38:40.264+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://storage-capstone/olist_sellers_dataset.csv; reason: notFound, message: Not found: URI gs://storage-capstone/olist_sellers_dataset.csv
[2024-05-04T11:38:40.281+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_sellers, execution_date=20240503T000000, start_date=20240504T113835, end_date=20240504T113840
[2024-05-04T11:38:40.304+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 198 for task gcs_to_bq_sellers (404 Not found: URI gs://storage-capstone/olist_sellers_dataset.csv; reason: notFound, message: Not found: URI gs://storage-capstone/olist_sellers_dataset.csv; 11181)
[2024-05-04T11:38:40.362+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T11:38:40.381+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:38:40.388+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
