[2024-05-03T13:31:58.914+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T13:31:59.052+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.upload_file_name manual__2024-05-03T13:31:41.829067+00:00 [queued]>
[2024-05-03T13:31:59.100+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.upload_file_name manual__2024-05-03T13:31:41.829067+00:00 [queued]>
[2024-05-03T13:31:59.107+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-03T13:31:59.222+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_name> on 2024-05-03 13:31:41.829067+00:00
[2024-05-03T13:31:59.357+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6120) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T13:31:59.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'upload_file_name', 'manual__2024-05-03T13:31:41.829067+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp2lsb06pw']
[2024-05-03T13:31:59.427+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask upload_file_name
[2024-05-03T13:31:59.431+0000] {standard_task_runner.py:63} INFO - Started process 6189 to run task
[2024-05-03T13:31:59.664+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.upload_file_name manual__2024-05-03T13:31:41.829067+00:00 [running]> on host 0db60b1edb75
[2024-05-03T13:32:01.217+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='upload_file_name' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T13:31:41.829067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T13:31:41.829067+00:00'
[2024-05-03T13:32:01.220+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T13:32:01.242+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-03T13:32:01.261+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-03T13:32:01.273+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T13:32:01.305+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 110, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 525, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 168, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 307, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 284, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 213, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-05-03T13:32:01.332+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=upload_file_name, execution_date=20240503T133141, start_date=20240503T133159, end_date=20240503T133201
[2024-05-03T13:32:02.753+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task upload_file_name (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 6189)
[2024-05-03T13:32:02.855+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T13:32:03.105+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T13:32:03.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
