[2024-05-03T13:27:52.067+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: etl.upload_file_payments scheduled__2024-05-02T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
